spring:
    datasource: 
      url: jdbc:mysql://118.24.0.161:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    

logging:
  level:
    com.smt.dao: debug
    
    
mybatis:
  configuration:
    cache-enabled: false
    local-cache-scope: STATEMENT
    